#!/usr/bin/env bash

# start up test db and rpc server
echo "initializing db (test)..."
docker run -d -p 27017:27017 --name mongodb-test mongo >/dev/null
echo "initializing test rabbitmq (test)..."
docker run -d -p 5672:5672 -p 15672:15672 --name rabbitmq-test rabbitmq:3.8.19-management >/dev/null

# wait for rabbitmq to fully load up
# sleep 15

echo "________________________"
echo 

# build docker images
make -C services/radit-api-gateway
make -C services/radit-auth-service
make -C services/radit-customer-service
make -C services/radit-payment-service
make -C services/radit-product-service
make -C services/radit-order-service
make -C services/radit-api-transaction-worker

echo "________________________"
echo 

# remove test db and rpc servers
echo "killing test servers..."
docker rm -f mongodb-test
docker rm -f rabbitmq-test
 
echo

# start up and run
echo "spawning up containers..."
docker-compose up | egrep -i 'gateway'