#!/usr/bin/env bash

# start up test db and rpc server
echo "initializing db and ampq..."
docker run -d -p 27017:27017 --name mongodb-test mongo >/dev/null
docker run -d -p 5672:5672 -p 15672:15672 --name rabbitmq-test rabbitmq:3.8.19-management >/dev/null

# wait for rabbitmq to fully load up
# sleep 15

# build docker images
#make -C services/radit-api-gateway
#make -C services/radit-auth-service
#make -C services/radit-customer-service
#make -C services/radit-payment-service
make -C services/radit-product-service
#make -C services/radit-order-service
#make -C services/radit-api-transaction-worker

# remove test db and rpc servers
docker rm -f mongodb-test
docker rm -f rabbitmq-test

# start up and run
#docker-compose up